zetta_utils/convnet/architecture/primitives.py

New module primitives + sequential

Sequential + Module Primitives

---

zetta_utils/alignment/online_finetunner.py
zetta_utils/cli/__init__.py
zetta_utils/cli/main.py
zetta_utils/cli/traceback_supress.py
zetta_utils/log.py
zetta_utils/tensor_ops/__init__.py
zetta_utils/tensor_ops/traceback_supress.py

Reverts ZettaAI/zetta_utils#101

Revert "Basic trace suppress config"

---

.coveragerc
pyproject.toml

…est coverage requirements from the whole `lightning` submodule

chore: pinning some requirements; no test cov for `lightning`

---

zetta_utils/alignment/online_finetuner.py

Allows alignment of uint8 images

fix(online_finetuner): force convert img to float

---

.coveragerc
pyproject.toml
tests/unit/convnet/test_unet.py
zetta_utils/convnet/architecture/deprecated/__init__.py
zetta_utils/convnet/architecture/deprecated/unet.py
zetta_utils/convnet/architecture/primitives.py
zetta_utils/convnet/architecture/unet.py

* minor fix regarding downsample/upsample calls
* UpConv layer
* switch between residual and concatenated skip connections
* breaking: skip connection should occur before first upsample layer

Feat: UNet extensions 

---

zetta_utils/training/lightning/trainers/default.py

fix: implemented separate process for JIT saving

---

zetta_utils/layer/db_layer/datastore/backend.py

fix: datastore retry

---

specs/nico/inference/cns_misd/0_mask_img.cue
specs/nico/inference/cns_misd/1_gen_labels.cue
specs/nico/inference/cns_misd/2_px_disp.cue
specs/nico/training/aced_misd_cns/z1z2_enc_misd.cue
zetta_utils/alignment/field.py
zetta_utils/alignment/misalignment_detector.py
zetta_utils/training/lightning/regimes/alignment/misalignment_detector_aced.py

* updated MisalignmentDetectorACED regime and inference method
* final training spec
* specs for inference / preparing GT
* `gen_biased_perlin_noise_field` to generate the vector field with fixed median and maximum vector lengths.

feat: CNS misalignment detection regime and specs

---

zetta_utils/alignment/field.py

* remove some redundant copies and enable torchfield identity cache -> ~20% speedup
* bump initial lr and add lr schedule -> better accuracy near folds/cracks

perf(field): invert_field speed up

---

zetta_utils/mazepa_layer_processing/common/volumetric_callable_operation.py

fix: apply crop_pad after last write_proc

---

pyproject.toml

need to roll back cloudvolume / cloudfiles due to a bug

hotfix: rollback cloudvolume / cloudfiles version

---

tests/unit/geometry/test_vec.py
zetta_utils/geometry/bbox.py
zetta_utils/geometry/vec.py
zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py

2344e2b feels particularly ugly...

Fixing some rounding related issues

---

tests/unit/geometry/test_bbox_strider.py
zetta_utils/geometry/bbox_strider.py
zetta_utils/layer/volumetric/tools.py
zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py

Should speed up integration tests, and performance in general.

feat: selective parallelism

---

docs/source/subchunkable_apply_flow_quick_start_guide.rst

Not linking #470 to close on pull since #418 still exists.

docs: use doctest everywhere, update examples, add calls

---

pyproject.toml
tests/unit/convnet/architecture/test_convblock.py
tests/unit/convnet/architecture/test_unet.py
tests/unit/tensor_ops/test_common.py
zetta_utils/convnet/architecture/convblock.py
zetta_utils/convnet/architecture/deprecated/__init__.py
zetta_utils/convnet/architecture/deprecated/convblock.py
zetta_utils/convnet/architecture/deprecated/unet.py
zetta_utils/convnet/architecture/primitives.py
zetta_utils/convnet/architecture/unet.py
zetta_utils/tensor_ops/__init__.py
zetta_utils/tensor_ops/common.py

Ignoring the JIT case for testing.

Convblock changes from Kisuk

---

scripts/generate_everything_import.py
zetta_utils/api/v0.py
zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py
zetta_utils/ng/link_builder.py

* `scripts/generate_everything_import.py`
* skip import errors encountered during traversal
* fix missing new lines at end
* set default log level to `INFO`
* `make_ng_layer`
* change `layers` type to `Sequence[Tuple[str, str, Optional[str]]]`
* handle empty `source` entry (for layers of type `annotation`)

minor fixes

---

specs/cronjobs/gc.cue
specs/examples/training/ddp.cue
specs/examples/training/ddp_config.cue
zetta_utils/cloud_management/resource_allocation/gcloud/__init__.py
zetta_utils/cloud_management/resource_allocation/gcloud/compute/instance.py
zetta_utils/cloud_management/resource_allocation/k8s/__init__.py
zetta_utils/cloud_management/resource_allocation/k8s/cronjob.py
zetta_utils/cloud_management/resource_allocation/k8s/job.py
zetta_utils/cloud_management/resource_allocation/k8s/pod.py
zetta_utils/training/lightning/train.py

Tried to make hybird k8s plus instance group training work but encountered too many network issues. Proceeding in that direction doesn't seem worth it since it is much easier with k8s.
Also removed default taint tolerations in `job` so gc cronjob can run on the system pool.

feat(training): Multinode DDP with Kubernetes

---

.gitignore
pyproject.toml
tests/unit/assets/infos/scratch/layer_scratch0/info
tests/unit/assets/infos/scratch/layer_scratch1/info
tests/unit/assets/infos/scratch/layer_scratch2/info
tests/unit/assets/infos/scratch/layer_scratch3/info
tests/unit/assets/infos/scratch/layer_scratch4/info
tests/unit/common/test_path.py
tests/unit/layer/volumetric/cloudvol/test_backend.py
tests/unit/layer/volumetric/precomputed/test_precomputed.py
zetta_utils/common/__init__.py
zetta_utils/common/path.py
zetta_utils/geometry/bbox_strider.py
zetta_utils/layer/volumetric/cloudvol/backend.py
zetta_utils/layer/volumetric/precomputed/precomputed.py
zetta_utils/layer/volumetric/tensorstore/backend.py

Also updated `.gitignore` to add other Vim swap files.

Resolve to absolute paths before checking for locality / use absolutes for caching / use cloud-files

---

zetta_utils/cloud_management/resource_allocation/k8s/job.py
zetta_utils/training/lightning/train.py

Still needs testing on a cluster that supports Pod Failure Policies

feat: pod_failure_policy to ignore disruption

---

zetta_utils/training/lightning/train.py

fix(traiin): better default for nproc_per_node

---

zetta_utils/convnet/architecture/convblock.py

chore: get rid of isinstance in convblock

---

zetta_utils/training/lightning/trainers/default.py

adds callback to register wandb logger

---

zetta_utils/cloud_management/resource_allocation/k8s/job.py

fix(job): better completion status message

---

tests/unit/mazepa/test_id_generation.py
zetta_utils/mazepa/id_generation.py

Happens e.g. here: https://github.com/ZettaAI/zetta_utils/blob/main/zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py#L253-L255

hotfix(id_generation): handle properties

---

pyproject.toml
scripts/benchmark_rigidity_map.py

...and a benchmark script to measure its performance

add weight_map to get_rigidity_map_zcxy function

---

scripts/benchmark_rigidity_map.py
zetta_utils/augmentations/tensor.py
zetta_utils/tensor_ops/convert.py
zetta_utils/tensor_ops/transform.py

Probably also requires https://github.com/ZettaAI/alignment/pull/4

chore(mypy): Pytorch 2.2.0 changes

---

zetta_utils/cli/main.py
zetta_utils/cloud_management/resource_allocation/k8s/common.py
zetta_utils/run/__init__.py
zetta_utils/training/lightning/train.py

refactor: main process identification, run record

---

zetta_utils/mazepa_addons/configurations/execute_on_gcp_with_sqs.py

fix: `local_test` without GCP ctx mngr

---

zetta_utils/mazepa_addons/configurations/execute_on_slurm.py

fix: arg list too long for slurm

---

build_image.py
docker/Dockerfile.all.p311

chore: deprecate p39 docker builds

---

.github/workflows/testing.yaml
.github/workflows/testing_integration.yaml
docker/Dockerfile.all.p310
docker/Dockerfile.all.p311
pyproject.toml
tests/unit/mazepa_layer_processing/segmentation/test_watershed.py
zetta_utils/mazepa_layer_processing/segmentation/__init__.py
zetta_utils/mazepa_layer_processing/segmentation/watershed.py

This PR adds the watershed function, with options to use either `abiss` or `lsd` (distance transform then `mahotas`'s watershed).
* TODO
* Add an example spec
* (later): Add an actual test with output comparison

Add watershed functions

---

scripts/gcp/create_corgie_igneous_cluster.py

fix(scripts): Reorder service account creation

---

docker/Dockerfile.all.p310
docker/Dockerfile.all.p311
zetta_utils/mazepa_addons/configurations/worker_pool.py

Fix `waterz` runtime compilation

---

zetta_utils/convnet/utils.py

fix(load_and_run_model): Accepts torch.tensor / np.ndarray

---

tests/unit/augmentations/test_misalign.py
zetta_utils/augmentations/misalign.py

Other changes:
- fixed & cleaned up typing (e.g., torch.Tensor→TensorTypeVar, list→Sequence)
- add saving misalignment metadata for downstream operations

fix(aug/misalignment): change to px displacement

---

tests/unit/augmentations/test_imgaug.py
zetta_utils/augmentations/imgaug.py

3d mode applies the same aug across sections

feat(imgaug): add 3d mode

---

tests/unit/layer/volumetric/test_tools.py
zetta_utils/layer/volumetric/tools.py

Also change output mask type to uint8 by default

feat(training/ROIMaskProcessor): add upstream_pad

---

scripts/assign_syn_simple.py
scripts/assign_synapses.py

These are essentially personal scripts, but per discussion with Sergiy, I'm just dropping them into the scripts folder for now.

Add two synapse-related scripts.

---

zetta_utils/training/lightning/trainers/default.py

See https://github.com/wandb/wandb/issues/8217

typing: wandb bug causes mypy error

---

tests/unit/geometry/test_bbox.py
zetta_utils/geometry/bbox.py
zetta_utils/layer/volumetric/index.py

(I'm going to need this to properly support chunk-crossing lines in AnnotationLayer.)

Add BBox3D.line_intersects and related code

---

tests/unit/geometry/test_bbox_strider.py
tests/unit/layer/volumetric/cloudvol/test_backend.py
tests/unit/layer/volumetric/precomputed/test_precomputed.py
tests/unit/layer/volumetric/test_tools.py
zetta_utils/geometry/bbox_strider.py
zetta_utils/layer/volumetric/cloudvol/backend.py
zetta_utils/layer/volumetric/cloudvol/build.py
zetta_utils/layer/volumetric/precomputed/precomputed.py
zetta_utils/layer/volumetric/tensorstore/build.py
zetta_utils/layer/volumetric/tools.py
zetta_utils/mazepa_layer_processing/common/__init__.py
zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py
zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py

Supporting PR for the internal PCG ingest PR.

rename bbox_strider arg, refactor subchunkable bbox parsing, add args to precomputed, fix CVBackend write behaviour

---

zetta_utils/db_annotations/annotation.py
zetta_utils/run/gc.py

Precomputed annotations do not support portal attributes, this pr makes them optional.

fix(db_annotations): dict - replace del with pop

---

tests/unit/geometry/test_bbox.py
zetta_utils/geometry/bbox.py
zetta_utils/layer/volumetric/index.py

Fixes issues with floating point behaviour when using decimal resolutions.

fix: numerical stability on decimal resolutions

---

scripts/gcp/create_corgie_igneous_cluster.py

...also fixes a typo and removes the region restriction

Lower cluster keda pod requests

---

zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py

chore: remove print statement

---

compile_waterz
docker/Dockerfile.all
docker/Dockerfile.all_pcg
install_zutils.py
pyproject.toml
setup_python.sh

One script that installs `zetta_utils` including all of the necessary apt-get packages and setting all the necessary environment variables. Designed to be usable in the docker file as well to reduce overall duplication.

feat: install script

---

tests/unit/assets/infos/layer_x2/info
tests/unit/training/datasets/conftest.py
tests/unit/training/datasets/test_collection_dataset.py
zetta_utils/layer/layer_set/backend.py
zetta_utils/layer/layer_set/build.py
zetta_utils/training/datasets/__init__.py
zetta_utils/training/datasets/collection_dataset.py

Build a dataset out of an annotation collection.
Annotation collection consists of annotations (shapes, boxes) and the associated layer groups. The collection based dataset will build a corresponding layer set and build a dataset.

Collection based dataset

---

zetta_utils/mazepa_layer_processing/common/interpolate_flow.py

Fixes https://github.com/ZettaAI/zetta_utils/issues/893

fix(interpolate): handling different src/dst

---

zetta_utils/mazepa/execution.py
zetta_utils/mazepa/progress_tracker.py
zetta_utils/mazepa_addons/configurations/execute_locally.py
zetta_utils/mazepa_addons/configurations/execute_on_gcp_with_sqs.py

setting `write_progress_summary` to `True` makes the console progress bar look weird

feat: write out progress report when flag is set

---

scripts/synapse_analysis.py

Add new synapse_analysis script.
Add support for reading CSV to synapse_analysis script.
Removed unneeded import
Slight refactor to main program.

Add synapse_analysis script (comparing predicted to GT synapses).

---

tests/unit/db_annotations/test_precomp_annotations.py
zetta_utils/db_annotations/precomp_annotations.py
zetta_utils/layer/volumetric/backend.py

Refactors AnnotationLayer to be a Backend subclass.

AnnotationLayer as a Backend subclass

---

pyproject.toml

https://github.com/ZettaAI/waterz/tree/tri/agg

Update waterz for semantic constraints

---

zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py

Need to focus on other things, so this will do for now.

fix: use slower O(n^2) algorithm for reduction chunk assignment for now

---

.gitmodules

feat(vscode-ext): Add submodule for extension

---

scripts/cave_synapse_mgr.py

See Slack discussion [here](https://zettaai.slack.com/archives/C015WPPL02J/p1756141528970959?thread_ts=1755909435.685959&cid=C015WPPL02J).

Add additional indexes to supervoxel tables.

---

tests/unit/test_builder.py
zetta_utils/builder/built_in_registrations.py

This limit slows me down, but it does not prevent loading and executing arbitrary code...

fix(lambda): remove character limit

---

zetta_utils/run/__init__.py

fix(run): wait for timer thread completion

---

pyproject.toml

CI didn't run tests because no python file changes, but I ran unit tests manually and they passed.

chore: update some seunglab dependencies
