ZettaAI/zetta_utils

specs/examples/training/mimic_encoder_brightness.cue
tests/unit/augmentations/test_tensor.py
zetta_utils/augmentations/tensor.py
zetta_utils/tensor_ops/convert.py

Adds brightness augmentation to simulate stitching patterns, with example cue file

Square tiling pattern augmentation with example

---

tests/unit/convnet/test_convblock.py
tests/unit/convnet/test_unet.py
zetta_utils/convnet/architecture/convblock.py
zetta_utils/convnet/architecture/unet.py

When dicts get deserialized from `cue/json/yaml`, the keys are always forced to be strings.
As the result `specs/examples/trainings/mimic_encoder.cue` wouldn't run on `main` as is.

fix: make skips `Dict[str, int]` to allow deserialized dicts

---

scripts/gcp/create_corgie_igneous_cluster.py
zetta_utils/mazepa_addons/resource_allocation/gcp_k8s.py

* add a tiny separate node pool to run system pods for autoscaler
* add Taint `worker-pool` to CPU/GPU node pools to prevent system pods from getting scheduled on worker nodes
* add Toleration for `worker-pool` taint to mazepa generated deployments

feat: set up CPU/GPU cluster with node autoscaler support

---

zetta_utils/typing.py

This allows static and runtime type checking to accept `VecND` for all methods that accept `Sequence`.

fix: _VecND inherits from abc.Sequence

---

zetta_utils/parsing/ngl_state.py

Both, `annotation.point` and `resolution` are of type `ndarray`, causing the dynamic typechecker to complain in `VolumetricNGLIndexer`

fix: Ensure Vec3D for point annotation

---

pyproject.toml

There is some weirdness with OpenCV requiring an XServer running - initially my local training simply wouldn't start without error message. Starting an XServer, it failed loading the Qt backend...
Since we don't rely on any OpenCV GUI stuff, would it be OK to just switch to the headless version?

fix: swap to headless OpenCV to avoid Qt/WSL/XServer issues

---

zetta_utils/geometry/vec.py
zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py

The Sequence type condition got lost somewhere in #245.
mypy doesn't complain about the missing `T_co`, but pylance does in a cryptic `Cannot create consistent method ordering` message.

fix: restore 7f8abe2

---

docs/source/zetta_utils.training.rst
tests/unit/training/datasets/test_chain_indexer.py
zetta_utils/training/datasets/sample_indexers/__init__.py
zetta_utils/training/datasets/sample_indexers/chain_indexer.py

A similar behavior would also be possible with Vertical Joint Datasets, but having a dedicated chain indexer should help keep the spec files more readable.

feat: ChainIndexer to chain SampleIndexers

---

zetta_utils/convnet/architecture/primitives.py
zetta_utils/layer/layer_base.py
zetta_utils/layer/tools_base.py

Provides access to all the builtins in `torch`, `torch.nn.functional`, `torch.linalg` and `torch.fft`.
It will not work with all function signatures (the ones that don't expect the tensor as first input), but I hope the easy accessibility of a wide range of operations may outweigh the few edge cases

Register public torch methods

---

tests/unit/mazepa/test_task.py
zetta_utils/mazepa/__init__.py
zetta_utils/mazepa/execution_queue.py
zetta_utils/mazepa/remote_execution_queues/sqs_queue.py
zetta_utils/mazepa/task_outcome.py
zetta_utils/mazepa/tasks.py

Lets the user specify which Exceptions/Text indicate a transient error and should be retried, rather than aborting execution.
These specification are passed to `@taskable_operation`/`@taskable_operation_cls` decorators to allow fine grained control over which tasks should be retried in which conditions. Some reasonable default set of transient exceptions is provided.
Transient errors will be ignored only if the task has been attempted less than a certain number of times, and will error out aborting the execution after that. This is because some errors (aka NVIDIA driver) can be both transient or non-transient.

feat: TransientError handling for mazepa executions

---

zetta_utils/mazepa/tasks.py

Still considering this a temporary fix. Both exceptions are legitimate and should not be retried when they occur on an instance without GPU or incorrect CUDA setup.

fix(mazepa): Another Runtime error caused by expired grace period

---

tests/unit/layer/volumetric/test_tools.py
zetta_utils/geometry/bbox_strider.py
zetta_utils/layer/volumetric/tools.py
zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py

Came up with a much cleaner way to do it after I wrote a lot of code for splitting into 3D; I'm leveraging the fact that the chunks are in row-major order already.

optimisation: remove quadratic scheduling

---

zetta_utils/mazepa/execution_state.py
zetta_utils/mazepa_layer_processing/common/interpolate_flow.py

Overlapping bounding boxes led to duplicate tasks from different parent flows.
* duplicate tasks now correctly track and update all associated parent flows upon completion
* duplicate tasks are now excluded from the progress report tally / reported counts should now line up with the dryrun results
Unrelated: `interpolate_flow` tasks would not receive a consistent hash across runs due to a `functools.partial` memory adress in the `TaskableOperation.__repr__()`
* switched to `ComparablePartial` for now, but something similar could easily happen in other places, I imagine.

Fixes regarding duplicate tasks

---

zetta_utils/mazepa/execution.py

Subchunkable creates own Executor on remote workers - those must not write to the same checkpoint location as the scheduler.

fix(mazepa/execution): Disable local execution checkpointing by default

---

.github/workflows/docs_deployment.yaml
.github/workflows/testing.yaml
.github/workflows/testing_integration.yaml

Fixed in https://github.com/actions/cache/releases/tag/v3.0.1
which is used by `setup-python@v4`

chore/fix: update actions versions fixes 2GB cache limit

---

zetta_utils/tensor_ops/convert.py

Current behavior ignores the desired `device` for `torch.Tensor` input. Change of default value to `None` to keep the current device and not accidentally move a GPU tensor back to CPU

fix(to_torch): respect device setting for torch.Tensor

---

zetta_utils/mazepa_layer_processing/alignment/common.py
zetta_utils/mazepa_layer_processing/alignment/warp_operation.py

Necessary for when field's `data_resolution` is coarser than the src `data_resolution`

feat: `translation_granularity` for field-adjusted download

---

specs/tommy/lee_fly_cns_segmentation_test001/230608_adjust_affinities.cue
specs/tommy/lee_fly_cns_segmentation_test001/230608_detect_three_image_masks.cue
specs/tommy/lee_fly_cns_segmentation_test001/230610_detect_three_resin_masks.cue
specs/tommy/lee_fly_cns_segmentation_test001/230612_copy_affinities.cue
specs/tommy/lee_fly_cns_segmentation_test001/230612_rework_affinities.cue
specs/tommy/lee_fly_cns_segmentation_test001/230612_rework_affinities_test.cue
specs/tommy/lee_fly_cns_segmentation_test001/detect_three_image_masks.cue
specs/tommy/lee_fly_cns_segmentation_test001/upsample_add_one.cue
zetta_utils/mazepa_layer_processing/__init__.py
zetta_utils/mazepa_layer_processing/segmentation/__init__.py
zetta_utils/mazepa_layer_processing/segmentation/masks/__init__.py
zetta_utils/mazepa_layer_processing/segmentation/masks/affinities.py
zetta_utils/mazepa_layer_processing/segmentation/masks/masks.py

These are some functions and specs that I used recently to adjust masks and affinities ahead of watershed and agglomeration. They will likely be useful for other segmentations. See commit messages and docstrings for more details. If these look reasonable, I'll add tests.

feat: adjust masks and affinities for segmentation

---

zetta_utils/builder/build.py
zetta_utils/builder/built_in_registrations.py

`from __future__ import annotations`  helps for static type checkers, but runtime checks will fail, e.g.:
```
│ zetta/zetta_utils/zetta_utils/builder/built_in_registrations.py:23 in                            │
│ efficient_parse_lambda_str                                                                       │
│                                                                                                  │
│ zetta/zetta_utils/venv/lib/python3.9/site-packages/typeguard/_decorators.py:140                  │
│ in wrapper                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: isinstance() arg 2 must be a type or tuple of types
```

fix(typing): Typeguard exceptions with X | Y union type under Python3.9

---

zetta_utils/mazepa_layer_processing/alignment/compute_field_flow.py

Forgot to mention this one to @dodamih before #460 
Although, glancing at the current logic (see below), I believe `skip_intermediaries` always must be `not self.intermediaries_dirs` - maybe we can just get rid off it?
https://github.com/ZettaAI/zetta_utils/blob/59e53681c946bd335b3b46c9aff283a3b5d33986/zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py#L251-L276

fix(compute_field_flow): skip intermediaries if possible

---

scripts/generate_everything_import.py
tests/unit/test_load_all_modules.py
zetta_utils/api/v0.py
zetta_utils/cloud_management/resource_allocation/aws_sqs.py
zetta_utils/mazepa_addons/configurations/execute_on_gcp_with_sqs.py

Python spec files, which are still in the testing phase, can now pull in all primitives from the entire repo with:
```python
from zetta_utils.everything import *
```
The `everything.py` file is autogenerated by looking at the repo's source code, as doing it manually would be too hard to maintain. The generator ensures there aren’t any naming conflicts. If it finds any, it'll throw an error. If python specs get more popular, we might want to add a check for duplicates in our CI.
`everything.py` doesn't include anything from `convnet.architecture.deprecated`, as we don't have any old python specs to deal with. Python specs don’t have the versioning capabilities that the builder does, so we need to think of something different. One idea is to have different versioned `everything` files. For …

feat: Import Everything option for python-style specs (experimental)

---

tests/unit/geometry/test_bbox.py
tests/unit/geometry/test_bbox_strider.py
tests/unit/geometry/test_vec.py
zetta_utils/geometry/bbox.py
zetta_utils/geometry/bbox_strider.py
zetta_utils/geometry/vec.py
zetta_utils/layer/volumetric/tools.py

Resolves most of the floating point comparison issues: there are the obvious comparisons (`==`, etc.), for which you can now use `allclose`, but `ceil` and `floor` were more frequently cause for trouble in our code.
Typical example is `floor(0.6/0.2) -> 2`. Resolving this for now with `floor(round(0.6/0.2, 10))`, but it does look a bit ugly...

Rounding Issues... Round 2

---

pyproject.toml
zetta_utils/geometry/bbox_strider.py

Got rid of a type annotation due to this bug in typeguard: https://github.com/agronholm/typeguard/issues/380.
Decided to bump mypy while I was at it as well.
Fixes #457

hotfix: unannotate variable, bump typeguard and mypy

---

tests/integration/assets/outputs_ref/test_uint8_copy_bbox/128_128_40/2048-3072_2048-3072_2000-2001.gz
tests/integration/assets/outputs_ref/test_uint8_copy_bbox/128_128_40/2048-3072_2048-3072_2001-2002.gz
tests/integration/assets/outputs_ref/test_uint8_copy_bbox/128_128_40/2048-3072_2048-3072_2002-2003.gz
tests/integration/assets/outputs_ref/test_uint8_copy_bbox/128_128_40/2048-3072_2048-3072_2003-2004.gz
tests/integration/assets/outputs_ref/test_uint8_copy_bbox/128_128_40/2048-3072_2048-3072_2004-2005.gz
tests/integration/assets/outputs_ref/test_uint8_copy_bbox/info
tests/integration/assets/outputs_ref/test_uint8_copy_no_op_kwargs/128_128_40/2048-3072_2048-3072_2000-2001.gz
tests/integration/assets/outputs_ref/test_uint8_copy_no_op_kwargs/128_128_40/2048-3072_2048-3072_2001-2002.gz
tests/integration/assets/outputs_ref/test_uint8_copy_no_op_kwargs/128_128_40/2048-3072_2048-3072_2002-2003.gz
tests/integration/assets/outputs_ref/test_uint8_copy_no_op_kwargs/128_128_40/2048-3072_2048-3072_2003-2004.gz
tests/integration/assets/outputs_ref/test_uint8_copy_no_op_kwargs/128_128_40/2048-3072_2048-3072_2004-2005.gz
tests/integration/assets/outputs_ref/test_uint8_copy_no_op_kwargs/info
tests/integration/subchunkable/test_subchunkable.py
zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py

`test_uint8_copy_bbox` was a missing integration test.

feat: allow supplying no op_kwargs

---

zetta_utils/training/lightning/trainers/default.py

The change in https://github.com/ZettaAI/zetta_utils/commit/9ea669ae5e9af364819975d81f4574d6c47f0c0d#diff-d7d24b371be4f087d00da084cea4983bbfe8e1d72f12ea6e737c6233d8cae702R103 overrides or unsets the `project` and `name` of the run, causing wandb to assign random names instead.
This PR should fix it, but I am not sure if that affects your DDP work, @akhileshh?

fix(ZettaDefaultTrainer): restore wandb project/run naming

---

specs/cronjobs/gc.cue
zetta_utils/cloud_management/resource_cleanup.py

Looks like some entries were missing sqs region (set to `""` somehow). This was causing the gc to crash.

fix(garbage-collection): sqs region fix

---

zetta_utils/cloud_management/resource_allocation/k8s/cronjob.py
zetta_utils/cloud_management/resource_allocation/k8s/deployment.py
zetta_utils/cloud_management/resource_allocation/k8s/pod.py
zetta_utils/mazepa_addons/configurations/execute_on_gcp_with_sqs.py
zetta_utils/training/lightning/train.py

Current behavior uses the worker_resources as both, lower and upper bound.
This PR allwos specifying a separate lower bound. (E.g. I want to ensure my process has 1 vCPU, but not throttle it if it goes beyond).
I tried to make it as backward compatible as possible, which is why the old name and argument order is preserved for public methods, but not sure if that causes confusion?

feat(k8s): allow distinct resource limits/requests

---

pyproject.toml
zetta_utils/message_queues/base.py

Added a bunch of `X | Y` hints in my last PR within a typechecked function that made typeguard unhappy. Version bump fixes it.
Also fixes accidental git import

chore: typeguard version bump

---

tests/unit/tensor_ops/test_convert.py
zetta_utils/tensor_ops/convert.py

In the same manner as uint64 because torch doesn't like uint

fix: workaround for reading uint32 data

---

mypy_plugin.py
tests/unit/tensor_ops/test_common.py
zetta_utils/tensor_ops/common.py
zetta_utils/tensor_ops/convert.py
zetta_utils/tensor_ops/mask.py

Should resolve #447.
Only needed it for `rearrange` and `crop` to work with my input/output layer set, though.

Support mapping as input for most tensor ops

---

tests/unit/layer/volumetric/test_tools.py
zetta_utils/layer/volumetric/__init__.py
zetta_utils/layer/volumetric/tools.py

Useful for applying a single 2D section across a 3D volume, e.g., a rotation field.

feat: add VolumetricIndexOverrideStartOffset

---

pyproject.toml
tests/unit/cli/test_cli.py
tests/unit/parsing/test_json.py
zetta_utils/builder/build.py
zetta_utils/cli/main.py
zetta_utils/cloud_management/execution_tracker.py
zetta_utils/parsing/__init__.py
zetta_utils/parsing/cue.py
zetta_utils/parsing/json.py
zetta_utils/training/lightning/train.py
zetta_utils/training/lightning/trainers/default.py

With this PR, tuples will be JSON encoded as list with a `__tuple__` marker as first element. The tuple preservation is required for libraries that differentiate between Python tuples and lists, i.e. `imgaug` treats tuples as value ranges to pick from, but JSON silently converts them to lists (discrete values)
Slows down JSON encoding/decoding a bit, but I don't think we use JSON for high-performance operations, anyway.

feat: preserve tuples in JSON

---

tests/unit/layer/volumetric/precomputed/test_precomputed.py
zetta_utils/layer/volumetric/cloudvol/build.py
zetta_utils/layer/volumetric/precomputed/precomputed.py

For issue https://github.com/ZettaAI/zetta_utils/issues/500.
Update 10/6/23: `add_scales_ref = None` (default) will use the highest resolution scale as reference.
Annotated example of current implementation:
```
{
"@type": "build_cv_layer"
path: #DST_PATH
ref_info: ...
// add_scales_ref can either be a dictionary
add_scales_ref: {
"key": "4_4_40",
"resolution": [4, 4, 40],
"chunk_sizes": [[512, 512, 1]],
"encoding": "raw",
"size": [1000, 1000, 1000],
"voxel_offset": [0, 0, 0]
}
// Or an existing key from `ref_info` from which the dict will be copied from.
// Throws an error if `ref_info` if key is not found
add_scales_ref: [4, 4, 40]
// Or `None` to use the highest resolution scale
add_scales_ref: null
// Example adding 3 scales.
add_scales: [
{
// Example of a fully speced entry
"key": …
```

Initial implementation of info_add_scales

---

pyproject.toml
zetta_utils/training/lightning/regimes/alignment/base_encoder.py
zetta_utils/training/lightning/regimes/alignment/encoding_coarsener.py
zetta_utils/training/lightning/regimes/alignment/encoding_coarsener_gen_x1.py
zetta_utils/training/lightning/regimes/alignment/encoding_coarsener_highres.py
zetta_utils/training/lightning/regimes/alignment/minima_encoder.py
zetta_utils/training/lightning/regimes/alignment/misalignment_detector.py
zetta_utils/training/lightning/regimes/alignment/misalignment_detector_aced.py
zetta_utils/training/lightning/regimes/common.py
zetta_utils/training/lightning/regimes/naive_supervised.py
zetta_utils/training/lightning/train.py
zetta_utils/training/lightning/trainers/default.py

Had to disable multiprocessing for the jit/onnx export to work at all. I don't think it's a big slowdown - depends on the validation intervall, of course.
Upgrade is probably a good idea anyway, but main reason is the newer pytorch-lightning gave more reliable exceptions when testing DDP (and there may be a chance it fixes bugs with DDP we are unaware of).
Necessary changes in more detail:
* `validation_epoch_end` is now `on_validation_epoch_end` and has no return type
* `pytorch_lightning.utilities.distributed import distributed_available` was removed - it's was a one-liner I added to zetta_utils
* `pytorch_lightning.utilities.cloud_io` was moved to `lighning_fabric.utilities.cloud_io` (and got typings!)
* `pl.callbacks` is intialized later, which caused mypy to complain in our init. I …

pytorch-lightning upgrade

---

.github/workflows/testing.yaml
.github/workflows/testing_integration.yaml
zetta_utils/cloud_management/resource_allocation/k8s/__init__.py
zetta_utils/cloud_management/resource_allocation/k8s/deployment.py
zetta_utils/cloud_management/resource_allocation/k8s/volume.py
zetta_utils/mazepa_addons/configurations/execute_on_gcp_with_sqs.py
zetta_utils/training/lightning/train.py

Also moved creation of `dshm` and `tmp` volumes because they were repeated, and pylint was complaining about having too many statements in `_lightning_train_remote`

feat(train): adds node_selectors based on provision_model

---

zetta_utils/mazepa_layer_processing/alignment/compute_field_flow.py
zetta_utils/mazepa_layer_processing/alignment/compute_field_multistage_flow.py

Needed `expand_bbox_resolution` for some of the recent encoder+misd preparation specs, which wasn't passed to the subchunkable flow so far.

feat(compute_field_flow): Add missing expand_bbox options

---

zetta_utils/cloud_management/resource_allocation/k8s/common.py
zetta_utils/cloud_management/resource_allocation/k8s/job.py

fix(k8s): wait until backoff_limit is reached for failed jobs

---

tests/unit/mazepa/test_id_generation.py
zetta_utils/mazepa/id_generation.py

Should now work for most custom classes, not just `TaskableOperation` and `partial` / `BuilderPartial`. Performance might be worse, though.

fix(id_generation): recursive hashing of class methods and custom attribs

---

zetta_utils/convnet/utils.py
zetta_utils/training/lightning/train.py

The CPU scheduler node might still fail to load the weights file during initialization, e.g. if it contains unsupported data types. This may be a scenario where we just want to skip the sanity checks on scheduler side entirely...

feat(train): start remote GPU training from instance without GPU

---

docs/source/subchunkable_apply_flow_quick_start_guide.rst
zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py

Removing dynamically skipped intermediaries for the top level until I can write the lookahead logic for skipping as many levels as possible correctly.

hotfix: remove dynamic intermediaries for top level, fix doc examples

---

.github/workflows/testing_integration.yaml

The `orjson.JSONDecodeError` occured because the LFS pointers were not converted - so zutils attempted to read the pointers rather than the actual file content.
The integration tests still fail, but the first subchunkable tests are now passing again: https://github.com/ZettaAI/zetta_utils/actions/runs/7709264157/job/21010085787

fix(testing_integration): resolve LFS pointers

---

tests/unit/layer/volumetric/test_tools.py
zetta_utils/layer/volumetric/__init__.py
zetta_utils/layer/volumetric/tools.py

Should be fully backward compatible (just have to rename `VolumetricStartOffsetOverrider` with `VolumetricIndexOverrider`). I haven't seen it being used in any cue file, though.

feat(tools): Expand StartOffsetOverrider to IndexOverrider

---

tests/integration/assets/outputs_ref/test_uint8_copy_auto_divisibility/128_128_40/2048-3072_2048-3072_2000-2001.gz
zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py

Should resolve the failing integration test `uint8_copy_writeproc_multilevel_checkerboard` and weird Mandala artifacts in blended uint8 layers.
The backend layer data type was used causing truncation errors with every additional blended layer if the destination is using integer

fix(ReduceByWeightedSum): rounding for integer layers

---

tests/unit/mazepa/test_id_generation.py
zetta_utils/mazepa/id_generation.py
zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py

* made `generate_invocation_id` a bit more lenient regarding input parameter types... it doesn't really care about what objects go in, they all get serialized as a tuple
* added dedicated subchunkable flow test (with level intermediaries) to test_id_generation - it's one of the main objects used
* made the suggested change to identify the subchunkable_apply_flow based on its local variables

fix(subchunkable_apply_flow): generate deterministic flow_id

---

zetta_utils/mazepa_layer_processing/common/subchunkable_apply_flow.py
zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py

This blends by taking the maximum value in the overlapping region.  Useful for things like segment IDs, where if a segment in the overlap has been labeled by both chunks, we just want all chunks to agree on which ID to use — and max is an efficient, consistent choice.

feat: Added blend mode 'max'

---

tests/unit/tensor_ops/test_common.py
zetta_utils/tensor_ops/__init__.py
zetta_utils/tensor_ops/common.py

Pad a tensor to specified shape. This is a prereq for something else in `internal`

feat: add pad_center_to() wrapping torch.pad()

---

tests/unit/tensor_ops/test_mask.py
zetta_utils/tensor_ops/mask.py

Add `filter_cc3d()` as an alternative 3D mode of `filter_cc()`. I elected to make a new function to not clutter the existing implementation too much, but perhaps it's easy to combine them...

feat: add filter_cc3d()

---

zetta_utils/layer/volumetric/constant/backend.py
zetta_utils/layer/volumetric/tools.py

* `ConstantVolumetricBackend` would return a volume of `np.float64`, yet the `dtype` getter is fixed to `np.float32`
* `VolumetricIndexTranslator` now optionally supports slice rounding - default is `False`, which matches the old behavior

Fix ConstantVolumetricBackend / Feat VolumetricIndexTranslator 

---

tests/unit/layer/volumetric/test_tools.py
zetta_utils/layer/volumetric/__init__.py
zetta_utils/layer/volumetric/tools.py

Needed that for a `VolumetricCallableOperation` with `res_change_mult` and output mask. I want to read the output mask at the output resolution, rather than the input resolution used for the EM data.

feat(tools): VolumetricIndexScaler

---

zetta_utils/layer/volumetric/cloudvol/backend.py

If not specified, CloudVolume will [pick a resonable compression mode based on the data encoding](https://github.com/seung-lab/cloud-volume/blob/355c85ba6b3c795a94eaf6e418e99cfeecf365c1/cloudvolume/datasource/precomputed/common.py#L12-L19).
Attempting to gzip JPG or PNG images is inefficient, but more importantly, it also seems to confuse CloudVolume and/or GCS when reading back the data: I keep getting checksum errors when trying to read these double-compressed images.

fix(cloudvol/backend): Use default (auto) compression mode

---

zetta_utils/layer/volumetric/precomputed/precomputed.py
zetta_utils/parsing/ngl_state.py

I tend to modify info files more frequently during development and it always caused trouble. CloudVolume's `commit_info` hardcoded this as well to `no-cache`.
Also found a similar `put_json` call for the remote annotations, which I reckon act very much the same.

Disable CDN cache for volatile JSON objects

---

tests/unit/layer/volumetric/cloudvol/test_backend.py
zetta_utils/layer/volumetric/cloudvol/backend.py

Just adds the actual cloudpath that was causing the `ScaleUnavailableError`

feat(cloudvol.backend): ScaleUnavailableError with path

---

tests/unit/tensor_ops/test_generators.py
zetta_utils/tensor_ops/generators.py

Similar to `torchfields.affine_field`, but supports generating fields represented by a perspective 3x3 2D transform

feat(generators): get_field_from_matrix

---

zetta_utils/convnet/utils.py

Notes:
- `with torch.inference_mode()` uses less memory. Without it I'd run out of mem. Not sure if it's applicable only for JITs or also other checkpoint types.
- `output = tensor_ops.convert.astype(output, reference=data_in)` was necessary anyway for `TensorTypeVar`, but without it the returned tensor is not detached and moved to CPU.

fix: running jit models

---

.gitmodules

To be consistent with `internal` and to make my life easier when cloning (http:// doesn't use key and github disabled password based authentication a long time ago).

Change specs submodule from http:// to git://

---

tests/unit/geometry/test_bbox.py
zetta_utils/geometry/bbox.py
zetta_utils/layer/volumetric/index.py

1. Added `from_points`, `union`, and `contains` methods to BBox3D.
2. Clarified (and corrected minor typos in) doc strings in BBox3D.
3. In VolumetricIndex, modified `from_coords` so it take its resolution as a CUE-friendly sequence as well as a Vec3D; also registered it with the builder, so you can actually create one in a CUE file now.
4. Added `union` and `contains` methods to VolumetricIndex as well.
5. Added doc strings to VolumetricIndex, which previously had none.

Minor BBox3D/VolumetricIndex improvements

---

web_api/Dockerfile
web_api/app/painting.py
web_api/requirements.txt

Based on the comments in https://cloud.google.com/run/quotas#request_limits
* Remove 32 MiB request size limit by switching from uvicorn to hypercorn with HTTP/2 support
* Remove 32 MIB response size limit by using FastAPI Streaming response (which sets `Transfer-Encoding: chunked`)

HTTP/2 + Streaming Response

---

zetta_utils/mazepa/progress_tracker.py

Avoids the exception caused by the new pdbp, which uses `pdbp.set_trace`

fix(progress_tracker): Support for all debuggers with .set_trace()

---

tests/unit/db_annotations/test_precomp_annotations.py
zetta_utils/db_annotations/precomp_annotations.py

These changes enable the synapse detection and assignment pipeline to be run entirely from a CUE file, in principle making it usable from Zetta Portal.
(This is a high priority for @macrintr.)

feat: mazepa hooks for AnnotationLayer setup and post-process; build_annotation_layer builder

---

tests/unit/db_annotations/test_annotation.py
tests/unit/db_annotations/test_precomp_annotations.py
web_api/app/annotations.py
web_api/app/collections.py
web_api/app/layer_groups.py
web_api/app/layers.py
web_api/app/main.py
web_api/app/precomputed_annotations.py
zetta_utils/db_annotations/annotation.py
zetta_utils/db_annotations/collection.py
zetta_utils/db_annotations/layer_group.py
zetta_utils/db_annotations/precomp_annotations.py
zetta_utils/layer/db_layer/datastore/backend.py
zetta_utils/layer/db_layer/firestore/backend.py

Implements #797.
For PUT and DELETE verbs, it turned out to be simplest to treat the file as a unit, i.e., PUT replaces the entire file and DELETE deletes the file.  (This also seems like a good fit for the resource model of REST APIs.)
Some changes also affect the `/annotations` endpoint, which @akhileshh found was broken in the current version.  It should be fixed with this PR.

Precomputed_annotations web API (#797).

---

zetta_utils/mazepa_layer_processing/common/volumetric_apply_flow.py

As noted [on Slack](https://zettaai.slack.com/archives/C03TJ1FPJTD/p1728665060174609), I ran into a bug trying to use the "max" blend mode.
```
mazepa /home/joe/zetta_utils/zetta_utils/mazepa/execution_state.py: 138                                                                  
Task traceback: Traceback (most recent call last):                                                                                       
File "/opt/zetta_utils/zetta_utils/mazepa/tasks.py", line 99, in __call__                                                              
return_value = self._call_task_fn(debug=debug)                                                                                       
File "/opt/zetta_utils/zetta_utils/mazepa/tasks.py", line 79, in _call_task_fn …
```

Fix incorrect argument type to torch.maximum.

---

pyproject.toml
zetta_utils/builder/__init__.py

Updates CloudVolume (see https://github.com/seung-lab/cloud-volume/issues/641)
Allows cue specs with NaN support... kinda:
```json
{
"@type": "build_cv_layer"
"path":   "..."
"cv_kwargs": {
"background_color": { "@type": "np.nan"}
}
}
```

Support for `np.nan` background_color

---

zetta_utils/parsing/cue.py

Immediately shows incomplete fields, rather than `some instances are incomplete; use the -c flag to show errors or suppress this message` (see [documentation](https://cuelang.org/docs/reference/command/cue-help-vet/))

fix(parsing/cue): require all regular fields to be concrete

---

tests/integration/subchunkable/test_custom_op.py

When this test was written (several months ago), it exposed a bug (threw a RecursionError exception, I think).
Now the test completes successfully, so yay!  Seems the bug was fixed.  But now we have a test for it, so that's good, right?

Add test_custom_op.py to test RecursionError bug.

---

tests/unit/db_annotations/test_precomp_annotations.py
zetta_utils/db_annotations/precomp_annotations.py

(substantially speeds up finalization of large annotation files)

Performance optimization in precomp_annotations.subdivide

---

zetta_utils/layer/volumetric/layer_set/layer.py

Allows combining two layers with a read_proc, e.g. https://github.com/ZettaAI/specs/blob/main/nico/inference/chen_s1/11_fine_align_pairwise.cue#L196-L223
Already worked before, just the static type checker would complain.

fix/typing(layer_set): Allow layer set read_proc to return single layer

---

pyproject.toml
zetta_utils/layer/volumetric/__init__.py
zetta_utils/layer/volumetric/tensorstore/build.py

ts=0.1.33 is incompatible with some setups with the below error
```
WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
Traceback (most recent call last):
File "/tmp/pip-build-env-rqacn702/overlay/lib/python3.12/site-packages/setuptools_scm/_integration/pyproject_reading.py", line 36, in read_pyproject
section = defn.get("tool", {})[tool_name]
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'setuptools_scm'
```

fix(tensorstore): update tensorstore & builder import

---

docker/pytorch_base/Dockerfile

Most of the GCP VM's we use are Skylake without AVX512 support. Lowering the target microarch to v3 resolves the `Illegal instruction (core dumped)` error when importing `graph-tool`.
Pytorch still uses AVX512, if available. They do some runtime checks, I believe.

fix(docker/pytorch_base): configurable microarch

---

build_image.py

It's unintuitive that the actual docker tag is not identical to `--tag` argument given to the script. Too much know-how

build_image.py: `tag`->`tag_suffix`

---

pyproject.toml
zetta_utils/tensor_ops/common.py

feat: use tinybrain for image downsampling

---

.github/workflows/testing.yaml
.github/workflows/testing_integration.yaml

Due to skip_apt, we actually need the go / cue installs.

Revert "chore: remove superfluous go / cue installs"

---

zetta_utils/cloud_management/resource_allocation/k8s/deployment.py
zetta_utils/cloud_management/resource_allocation/k8s/job.py
zetta_utils/cloud_management/resource_allocation/k8s/pod.py
zetta_utils/training/lightning/train.py

* Separate thread to fetch logs from training worker pods (k8s logs call is blocking).
* Set explicit TTL for jobs so they get deleted after failure, releasing locked resources.

fix(train): set explicit ttl for k8s job to prevent run hanging

---

tests/unit/convnet/architecture/test_unet.py
zetta_utils/__init__.py

* Mypy doesn't know that `UNet`'s `ConvBlock` may have a `ModuleList` as layers as well... even with this fix (`Iterable`), it will assume those are `Tensors`... meh

minor CI issues (mypy+cov)

---

zetta_utils/training/lightning/trainers/default.py

`enable_progress_bar=False` otherwise fails with
``MisconfigurationException: Trainer was configured with `enable_progress_bar=False` but found `RichProgressBar` in callbacks list.``

fix(trainer): enable_progress_bar=False bypasses RichProgressBar
